spring.security.user.name=admin
spring.security.user.password=admin
spring.security.enabled=false

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/emailgen
spring.datasource.username=emailuser
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Logging
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE