spring.security.user.name=admin
spring.security.user.password=admin
spring.security.enabled=false

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/emailgen
spring.datasource.username=db_user
spring.datasource.password=db_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
